-- This module is the root of the PAdicHodgeTheoryCanonicalLaneLean Lean proof package.
import PAdicHodgeTheoryCanonicalLaneLean.Basic
import PAdicHodgeTheoryCanonicalLaneLean.SourcePackage
import PAdicHodgeTheoryCanonicalLaneLean.SourceDependencies
import PAdicHodgeTheoryCanonicalLaneLean.Formalization
import PAdicHodgeTheoryCanonicalLaneLean.ReviewerBridge
import PAdicHodgeTheoryCanonicalLaneLean.TheoremStatement
import PAdicHodgeTheoryCanonicalLaneLean.MathlibObjects
import PAdicHodgeTheoryCanonicalLaneLean.AdmissibleClass
import PAdicHodgeTheoryCanonicalLaneLean.Projection
import PAdicHodgeTheoryCanonicalLaneLean.BridgeLemmas
import PAdicHodgeTheoryCanonicalLaneLean.GateLemmas
import PAdicHodgeTheoryCanonicalLaneLean.FinalTheorem
import PAdicHodgeTheoryCanonicalLaneLean.MathlibStatement
